[package]
name = "totk-dump"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.10"
eyre = "0.6.8"
jwalk = "0.8.1"
parking_lot = "0.12.1"
rayon = "1.7.0"
roead = { path = "../roead", features = ["byml7", "with-serde"] }
serde_yaml = "0.9.21"
zstd = "0.12.3+zstd.1.5.2"
